[MISSING_PAGE_EMPTY:2]

[MISSING_PAGE_EMPTY:3]

[MISSING_PAGE_FAIL:4]

AVANCE ENEL

FORATELECMIENTO DEL BALANCE

(B) CRECimiento

Con la finalidad de mejorar los indicadores financeros de FibraShop e incrementar el retorno de inversion para los tenedores, el 29 de enero de 2024, FibraShop annuncio una serie de operaciones para su fortalecimiento del balance.

1.- Operaciones encaminadas al crecimiento.

2. Suscripcion de Certificados Fiducarios Inmoliliarios.

**1.OPERACIONES ENCAMINADAS AL CRECIMiento**

La primera, consistia en la aportacion de 3 propiedades con un valor originalmente aproximado de 1,800 millones de pesos pertenecientes a partes relacionadas -Sentura Tlalnepantla, Galerias San Juan del Rio y Sentura Zamora- y la asociacion de 2 immuebles -Via Paraiso y Puerto Paraiso-. Tanto la aportacion como la fusion fueron aprobadas por los organos de gobierno de la compania. El pago por la adquisicion de los 3 Centros Comerciales se realizaria de la siguiente manera:

* 1,400 mdp serian pagados con CBFIS a un valor de 6.50 pesos.
* Los 400 mdp restantes de liquidarian en **hasta un periodo de 24 meses** con el flujo operativo de la Fibra.

Actualmente **dicha adquisicion se encuentra en proceso de autorizacion de la Comision Federal de Competencia Economica (COFECE)**. Se espera obtener el fallo a durante el segundo trimestre de este ano.

Es importante senalar que, durante el cirrere de las negociaciones **se obtuvo una mejora en la adquisicion de Sentura Tlanepantla**, en la cual actualmente FibraShop es propietaria del 35% de la propiedad ya operada y consolidada en su balance.

La siguiente tabla muestra el cambio en el precio por el 65% de la propiedad:

**65%**

**Monte Anterior**

**Monte Actual**

**Variacion**

**Sentura Tlalnepantla**

**812 mdp**

**747 mdp**

**-8%**

**Por lo que el pago de la transaccion por las 3 propiedades quadaria como sigue:**

**Monte pactado**

**Noladquirado**

**CAP Rate**

**Sentura Tlanepantla (65%)**

**747**

**78**

**10.44%**

**Sentura Zamora**

**500**

**45**

**9%**

**Galerias San Juan del Rio**

**520**

**55**

**10.57%**

**TOTAL**

**1,767**

**178**

**10.07%**

**Se otorgaran 199,615,366 CBFIS a un precio de 6.50 pesos por titulo (1,297 mdp) y el restante (470mdp) se pagara en efectivo en hasta un periodo de 24 meses.

## 2 Suscripion de Certificados Filuciarios immobiliarios

La segunda, fue convocar a una Asamblea de Tenedores para darles la opcion de suscribir hasta por el porcentaje de su participacion a los inversionistas actuales. Considerandose un derecho para que su participacion no tuviere alguna modificacion.

La Asamblea de Tenedores para la aprobacion de la suscripcion se llevo a cabo con un quorum de 87.83%, en donde esta, por una differencia minima de votos, no fue aprobada. Tomanando en consideracion la estrategia de crecimiento y en busqueda de una mejora en os indicadores financieros y un mejor retorno para los inversionistas, se tomo la decision de continuar con las adquisiciones.

El Comite Tecnico en su sesion del pasado 18 de abril de este aho, accordo evaluar y replantear la Guia de Distribucion de Dividendos con base en las adquisiciones que impactaran en el numero de certificados en circulacion, asi como la disminucion en las tasas de interefs.

Para este trimestre se decreto un dividendo de 60 millones de pesos con un valor de 0.1371 pesos por CBFI, que anualizado de forma simple equivale a.5484 pesos por CBFI. Lo anterior, implica que estariamos alrededor del 70% del rendimiento pagado pre-pandemia.

[MISSING_PAGE_EMPTY:9]

## Chapter 2. Centro de Vida La

A continuacion se presentan los resultados de la Perla:

[MISSING_PAGE_EMPTY:11]

## 4. **Composicion DE INGRESOs**

* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.
* Del total de los contratos los que cobran una renta fija mensual representan el 67.19% del total.
* Del total de contratos los que cobran una renta base mensual, asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.

[MISSING_PAGE_POST]

 asi como un complemento variable relacionado con los ingresos del locatorio (renta variable), representan el restante 32.81%. Medido como porcentaje de los ingresos por concepto de renta, los contratos con renta fija representan el 72.69% y los que incluyen renta variable el 27.31%.

## Chapter 5 Calculo DEL MARGEN FIBPA OPERATVO DE LAS PLAZAS PLAZAS

El margen operativo de las plazas incluye los ingresos generados por cada propiedad y los gastos directamente relacionados al mantenimiento de los mismos; el resultado neto se determina agregando los gastos del arrendador:

\begin{tabular}{c c c c c c}  & **IT 2024** & **471023** & **3172023** & **217023** & **117023** \\ \end{tabular}

\begin{tabular}{c c c c c}  & **Total de ingresos** & **559.47** & **571.55** & **620.63** & **544.33** & **523.32** \\ \end{tabular}

\begin{tabular}{c c c c c c}  & **Gastos de operacion de las plazas** & **82.34** & **74.71** & **91.67** & **83.27** & **76.49** \\ \end{tabular}

\begin{tabular}{c c c c c}  & **Utillidad Operativa de las plazas** & **477.13** & **496.83** & **528.97** & **461.06** & **446.83** \\ \end{tabular}

\begin{tabular}{c c c c c}  & **Margen operativo de las plazas** & **85.28\%** & **86.93\%** & **85.23\%** & **84.70\%** & **85.38\%** \\ \end{tabular}

\begin{tabular}{c c c c c}  & **Gastos del arrendador (seguros, predial,** & & & & & & \\ **avalios, pasivo laboral)** & **17.08** & **20.64** & **17.90** & **21.68** & **17.43** \\ \end{tabular}

\begin{tabular}{c c c c c c}  & **Utillidad operativa meta de las plazas** & **460.05** & **476.20** & **511.06** & **439.38** & **429.40** \\ \end{tabular}

\begin{tabular}{c c c c c}  & **Margen operativo de las plazas** & **82.23\%** & **83.32\%** & **82.34\%** & **80.72\%** & **82.05\%** \\ \end{tabular}

## 6. DEUDA ACTUAL

7. CONVENANTS

En relacion a las emisiones de deuda, FSHOP17-2 y FSHOP19U, FibraShop tiene la obligacion de mantenerse dentro de los siguientes parametros:

El calculo del covenant del servicio de la deuda, se determina con los interesses ofectivamente pagados, sin tomar las comisiones de los financialimentos que ya fueron pagados de manera anticipada.

El calculo del covenant activos no gravados a deuda no garantizada toma en cuenta el total de activos que se encuentran dados en garantia que amparan la totalidad de la lineas de credito.

[MISSING_PAGE_FAIL:20]

[MISSING_PAGE_FAIL:21]

## 10. Cbfi's con derechos

EMP.

Economicos

Para este trimestre los certificados con derechos economicos son 437,500,058.

Economicos

Para este trimestre los certificados con derechos economicos son 437,500,058.

## 3 Enajenacion de inmuebles antes de haber transcurrido el plazo de 4 anos

[FIGURE:S3.F1][ENDFIGUR

[MISSING_PAGE_FAIL:24]

[MISSING_PAGE_FAIL:25]

[MISSING_PAGE_EMPTY:26]

[MISSING_PAGE_FAIL:27]

[MISSING_PAGE_EMPTY:28]

15. INFORMACION adicional

De acuerdo la Circular Unica de Emisoras (CUE) en base al articulo 33 fraccion II- Informacion

 Trimestral, se manda a la Bolsa Mexicana de Valores en los formatos electronicos

correspondientes informacion financera y contable adicional conteniendo la actualizacion de

 la informacion anual, y se puede consultar en www.bmv.com.mx

16. EVENTOS adicionnales

No hay eventos subsecuentes que deban ser revelados.

[MISSING_PAGE_FAIL:31]

[MISSING_PAGE_EMPTY:32]

## Appendix A Acerca de Fibrashop

FibraShop (BMV: FSHOP 13), es una opcion unica de inversion immobiliaria en Mexico, derivada de su especializacion, el capital humano con mayor experiencia en el sector immobiliario commercial, su solida estructura operativa y de gobierno corporativo, lo cual en su conjunto asegura transparencia, eficiencia y un crecimiento seguro y rentable.

FibraShop es un fidelicomiso de infraestructura y bienes raices constituido principalmente para adapuirir, poseer, administirar y desarrollar propiedades immobiliarias en el sector de centros comerciales en Mexico. FibraShop es administrada por especialistas en la industria con amplia experiencia y asesorada externamente por FibraShop Portafolios Immobiliarios, S.C.

Nuestro objetivo es proveer de atractivos retornos a nuestros inversionistas tenedores de los CBFIs, a traves de distribuciones estables y apreciacion de capital.

## Declaraciones Sobre Eventos Futuros

Este comunicado puede incluir declaraciones a futuro. Dichas declaraciones no estan basadas en hechos historicos sino en la vision actual de la administracion. Se advierte al lector que dichas declaraciones o estimaciones implican niesgos e incertidumbre que pueden cambiar en funcion de diversos factores que no se encuentran bajo control de la compania.

**INFORMACION FINANCIERA**

**CI Banco, S.A., Instituioioh de Banca Multiple**

**Fidelcomiso Irrevoable Numero F/00854 y Subsidarias**

**ESTADOOS DE RESULTADOS INTEGRAL CONSOLIDADOS**

**Por los periodos comprendidos del 1ro de enero al 31 de marzo 2024 y 2023**

**(Cifras expresadas en miles de pesos)**

**(No auditado**

1T 2024 1T 2023**

Ingresos por rentas 491,748 437,500**

**Otros ingresos operativos 67,723 85,820**

**Total de ingresos 559,471**

**523,320**

**Gasto de operacion:**

**Gastos operativos 125,210 107,051**

**Seguros 3,846 3,558**

**Honorarios del asesor 18,963 17,767**

**Honorarios professionales 1,791 1,907**

**Total de gastos de operacion 149,810 130,283**

**Utilidad de operacion 409,661 393,037**

**Costo de financialiemento:**

**Ingreso por intereses 8,835 9,260**

**Gasto por intereses 299,113 299,999**

**Costo de financialiemento, neto (290,278) (290,739)**

**Valuacion de deuda en UDIs (48,518) (46,013)**

**Utilidad neta consolidada 70,865 56,285**

**Resultado neto consolidado**

**attribuible a:**

**Participacion no controlada 8,535 16,966**

**Participacion controlada 62,330 39,319**

**Utilidad neta consolidada 70,865 56,285**

[MISSING_PAGE_FAIL:35]

INFORMACION FINANCIERA

CI Banco, S.A., Institucion de Banca Multiple

Fidelcomiso Irrevocable Numero F/00854 y Subsidarias

ESTADOS DE FLUIJOS DE EFECTIVO

Por los periodos comprendidos del 1ro de enero al 31 de marzo de 2024 y 2023

(Cirtes expresadas en miles de pesos)

(No auditado)

**Flujos de efectivo de actividades de operacion:**

Utilidad neta consolidada

70,865 56,285

Ajustes por:

Intereses a favor

Beneficios a los empleados

Bengciacion y amortizacion

5,170 4,115

Amortizacion de costo financiero

7,457 7,142

Reconomicoimento de ingressos en linea recta

- & 3,259

Valuacion deuda en UDIS

48,518 46,013

Intereses a cargo

414,736 398,862

Cuentas por cokrar

6,470 23,878

Partes relacionadas

Impustos por recuperar y otras cuentas por cokrar

Pagos anticipados

(13,597) (30,770)

Proveedores

Pasivos acumudados

Anticipos de clientes

Depositos on garantia de arrendataios

7,427 936

Flujos neto de efectivo obenidos de actividades de operacion

477,315 415,436

**Flujos netos de efectivo de actividades de inversion:**

Infreeses reckibidos

Inversiones en procoso, proyectos y activo fijo

8,693 11,070

(51,212) (148,411)

Flujos de efectivo netos generados (utilizados) en actividades de inversion:**

(42,519) (137,341)

**Flujos de efectivo de actividades de financiamiento:**

Infrees pagados

Creditos bancanios- Disposiciones realizadas

Creditos bancanios- Pagos realizados

Cornision por estructura crodito

(1,346) (409)

Distribucion a tenedores

Flujos netos de efectivo ( utilizados) en actividades de financiamiento

(305,145) (302,833).

Incemento (decremento) neto de efectivo y equivalentes de efectivo

129,651 (24,739)

Electivo y equivalentes de efectivo al inicio del año

**Efectivo y equivalentes de efectivo al final del periodo**

**EC1 Banco, S. A., Institucion de Banca Multiple

Fideicomiso Irrevocable Numero F/00854 y Subsidarias

**Notas a los estados financeros consolidados condensados intermediios**

**Por el periodo comprendido del 1 de enero al 31 de marzo de 2024**

**(No auditados, cifras en miles de pesos)**

## 1.1. Information general

FibraShop ("FSHOP") es un Fideicomiso de Inversion en Bienes Raices constituido mediante el contrato de Fideicomiso F/O0854 de fecha 21 de junio de 2013, que celebran por una parte Fibra Shop Portafoilos immobilizios, S.C (Fideicomiente), The Bank of New York Mellon, S.A. IBM (Hoy Cl Banco, S.A. IBM) (Fiduciario) y Deutsche Bank Mexico, S.A. IBM (Representante Comun) segun consta en la escritura publica numero 39,222 otorgada ante la fe del Lic. Jose Luis Villavicencio Castaneda, Notario Publico numero 218 del Distrito Federal. Su actividad principal es adquiir bienes que se destinen al arrendamiento y desarrollo de inmuebles de uso comercial, con domicilio Juan Salvador Agraz No. 65 Piso 21, Colonia Santa Fe, Cuajimalpa de Morelos, Ciudad de Mexico.

FibraShop, como un Fideicomiso de Inversiones en Bienes Raices ("FIBRA"), califica para ser tratado como una entiidad transparente en Mexico para fines de la Ley del Impuesto Sobre la Renta. Por lo tanto, todos los ingresso de la conduccion de las operaciones del Fideicomiso se attribuyen a los titulares de sus Certificados Bursatiles Fiduciarios Inmobilizios ("CBFIS") y el Fideicomiso no esta sujeto a Impuesto Sobre la Renta en Mexico. Para mantener el estado de FIBRA, la Secretaria de Hacienda y Credito Publico ("SHCP") establecio, en los articulos 187 y 188 de la Ley del Impuesto Sobre la Renta ("LISR") vigentes al 31 de diciembre de 2015 que el Fideicomiso debe distribuir anualmente al menos el 95% de su resultado fiscal neto a los titulares de sus CFBIs. Los CBFIS cotizan en la Bolsa Mexicana de Valores bajo la clave de pizarra FSHOP13, los cuales fueron ofertados publicamente el 24 de Julio de 2013, obteniendose un precio de colocacion por CBFI de 17.50 pesos.

## 2. Bases de preparacion

(a) Declaracion de cumplimiento

Estos estados financieros consolidados se prepararon conforme a los requisitos de las Normas Internacionales de Informacion Financiera ("NII") emitidas por la Junta de Normas Internacionales de Contabilidad (IASB por sus siglas en ingles). Estos estados financieros consolidados corresponden a FibraShop y a sus entiadas controladas, en adelante FSHOP.

FSHOP ha elegido presentar un solo estado consolidado de resultados integrales y presenta sus gastos por naturalez.

Los flujos de efectivo de sus actividades de operacion se informan bajo el metodo indirecto. Los ingresos por arrendamiento de propiedades, junto con los depositos recibidos y pagados, se trataran como flujos de efectivo de actividades de operacion. Las adquisiciones de propiedades de inversion se divulgan como flujos de efectivo de actividades de inversion, ya que reflejan de manera mas precisa las actividades comerciales de FSHOP.

La Administracion de FSHOP considera que todos los ajustes ordenarios y recurrentes necesarios para una adecuada presentacion de los estados financieros consolidados condensados intermedios fueron inculidos.

Estos estados financieros condensados consolidados se prepararon conforme a NIC 34 Informacion Financiera Intermedia. Las Notas explicitas se incluyen para revelar los eventos y las transacciones significativas para entender el desempeno de FSHOP. Los estados condensados consolidados trimestrales que se presentan no contienen toda la informacion y revelaciones requeridas en los estados financieros consolidados anuales.

El 18 de abril de 2024, el Comite Tecnico de FSHOP aprobo la presentacion de estos estados financieros condensados consolidados correspondientes al primer trimestre de 2024.

### (b) Criterios y estimaciones

La preparacion de los estados financieros condensados consolidados intermediios exige que la Administracion realice estimaciones y supuestos que afectan la aplicacion de las politicas contables, los importes reportados de activos y pasivos, ingresos y gastos. Las estimaciones y criterios se evaluan continuamente y se basan en la experiencia y gestiones de la Administracion asi como de otros factores, inculidas expectativas razonables sobre eventos futuros. La Administracion considera que las estimaciones utilizadas en la preparacion de los estados financieros condensados consolidados intermedios son razonables. Los resultados reales pueden diferir de dichas estimaciones y por lo tanto, es posible, sobre la base del conocimiento existente, que los resultados dentro del proximo año financiero sean diferentes de nuestros supuestos y estimaciones, que podria dar lugar a un ajuste a los importes previamente reportados de activos y pasivos.

En la preparacion de los estados financieros condensados consolidados intermedios, la Administracion adopto las politicas contables que se describen en las presentes notas, las cuales seran aplicadas de manera consistente hacia adelante, salvo que existan cambios importantes en las condiciones economicas o en las actividades de FSHOP que justifiquen un cambio en alguna de ellas. Las notas a los estados financieros consolidados establecen areas que involucran un grado de mayor criterio complejidad o areas donde las suposiciones son importantes para el informe financiero consolidado, como son la estimacion del valor razonable de propiedades de inversion, la estimacion de cuentas de cobro dudoso, entre otras.

La NIC 34 requiere estados de utilidad integral, de variaciones en el capital contable, de flujos de efectivo para los periodos intermedios comparativos (del periodo y acumulado) del año financiero anterior.

(d) Estacionalidad de Operaciones

Existen fluctuaciones estacionales para las operaciones de FibraShop dadas las caracteristicas de las propiedades y los contratos de arrendamiento en periodos tales como vacaciones de verano, epoca decembrina, principalmente.

## 3 Resumen de las Politicas Contables Significativas

Las principales politicas contables adoptadas en la preparacion de los estados financieros condensados consolidados intermedios son consistentes con las utilizadas en la preparacion de los estados financieros consolidados por el periodo enero - marzo 2024.

Bases de consolidacion

Los estados financieros consolidados de FSHOP incorporan los activos y pasivos de las entiadades controladas por FSHOP al primer trimestre de 2024. Se ellimanan los efectos de los balances y transacciones dentro del grupo y todos los ingresos y gastos no realizados derivados de transacciones dentro del grupo al preparar los estados financieros consolidados. Las entiadades controladas son aquellas entiadades sobre cuyas principales politicas financieras y de operacion FSHOP tiene la potestad de regir. Cuando se obtiene el control de un entidad durante un año, sus resultados se incluyen en el estado de resultados integrales consolidados desde la fecha en que se inciole el control. Cuando el control de un entidad cesa durante el año, se incluyen resultados para la parte del año durante la que existio control.

Informacion financiera por segmentos

Los segmentos de operacion se identifican segun informes internos sobre los componentes del Grupo que estan siendo revisados por la alta direccion y que han sido identificados como los principales encargados de la toma de decisiones operativas, para asignar recursos a segmentos y evaluar su desempeno.

Las propiedades comerciales que la mayoria de sus locatorios esten enfocados al negocio de moda, ropa y accessorios se les denominara Fashion Mall, aquellas en donde sus locatorios esten mas enfocados a la prestacion de servicios y que cuentan con una tienda de autoservicio seran denominados Power Center y finalmente las propiedades de menores dimensiones enfocadas a servicios seran denominadas Community Center.

La informacion sobre activos de inversion y segmentos se base en la informacion financiera derivada de la aplicacion de las principales politicas contables.

RECONOCOLIENTO DE INGRESOS

Los ingresos por ventas se cuantifican a valor razonable de la contraprestacion recibida o por recibir. Se reconconoen ingresos de ventas para cada fuente de ingresos por ventas principal de la siguiente manera:

#### Ingresos por arrendamientos

Los ingresos por arrendamientos de propiedades de inversion se reconconcon como ingresos de ventas en los estados financieros en terminos de los contratos de arrendamiento con los arrendatarios y en forma lineal durante el periodo de cada arrendamiento.

Se pueden ofrecer incentivos a los arrendatarios para que celebren contratos de arrendamiento operativos no cancelables. Estos incentivos pueden asumir varias formas, incluso periodos sin pago de arrendamiento, rentas escalonadas y variables, entre otros.

#### Ingresos por mantenimiento

Los ingresos por mantenimiento de las propiedades de inversion derivan escencialmente del costo de mantenimiento de las propiedades comerciales que son cobrados a los arrendatarios para el correcto funcionamiento y adecuada manutencion de las plazas comerciales.

#### Otros ingresos

Otros ingresos comprenden pagos recibidos en relacion con la terminacion de contratos de arrendamiento, asi como qualquier otro ingreso extraordinario que se llegue a presentar en el curso de las operaciones de FSHOP.

#### Participacion en Asociadas

La Norma Internacional de Contabilidad 28 ("NIC 28") Inversiones en Asociadas y Negocios Conjuntos, establece las bases para la contabilidad de las inversiones en asociadas, asi como los requerimientos para la aplicacion del metodo de la participacion al contabilizar las inversiones en asociadas y negocios conjuntos.

La Norma se aplica a todas las entidades que sean inversores con control conjunto de una participada o tengan influencia significativa.

## 1. EfECTIVO, Equivalentes de effective y efectivo restringido

\begin{tabular}{c|c c}  & Mar 2024 & Dic 2023 \\ \hline Efectivo en cuentas bancarias & 137,233 & 66,075 \\ Fondo de reserva para servicio de & & \\ deuda & 232,382 & 227,733 \\ Inversiones en valores & 186,840 & 132,996 \\
**Total de Efectivo, Equivalentes de** & **556,455** & **426,804** \\
**Efectivo y Efectivo Restringido** & & \\ \end{tabular}

## 2. Cuentas por cobarar

\begin{tabular}{c|c c}  & Mar 2024 & Dic 2023 \\ \hline Clientes & 435,264 & 441,744 \\ Estimacion para cuentas de cobro & (36,517) & (36,526) \\ dudoso & **398,748** & **405,218** \\ \end{tabular}

## 3. IMPUESTO AI VALOR AGREGADO por RECUPERAR

\begin{tabular}{c|c c}  & Mar 2024 & Dic 2023 \\ \hline IVA por recuperar & 198,427 & 214,309 \\ Otros Impuestos por recuperar & 7,935 & 5,458 \\
**Total de Impuestos a favor** & **206,362** & **219,767** \\ Otras cuentas por cobarar\({}^{*}\) & 539,000 & 558,929 \\ \end{tabular}

\({}^{*}\)La rengegociacion del monto por la liquidacion del immueb Puerto la Victoria determino un saldo a favor de Fibrashop por 292.70 millones de pesos, en noviembre de 2020. El 9 de Julio de 2021, se reciblo la notificacion de emplizamento de la demanda instaurada en contra de Fibrashop por parte del vendador del centro comercial "Puerta La Victoria". En dicha demanda manifeststan principalmente su desaucerdo respecto deljuste al precio que se deblo realizar al cierre del 2020. La controversia con el vendador continua desarrolladose, en cuando exista information relevante el respecto, sera revelada.

## 4 Propiedades de Inversion

Al 31 de marzo de 2024, el portafolio de propiedades de inversion de FSHOP (tomando en cuenta unicamente el GLA propiedad de FSHOP) esta conformado por 17 inmuebles.

\begin{tabular}{l|c c}  & Mar 2024 & Dic 2023 \\ \hline Propiedades de inversion & 25,401,904 & 25,463,014 \\ Mobilinario y equipo netos & 105,766 & 145,113 \\ Total & **25,507,670** & **25,608,127** \\ \end{tabular}

## 5 SWAP DE TASA DE INTERESTES

Los swaps de tasa de interes cumplen los criterios para ser reconocidos contablemente como una cobertura y cubre un credito bancario de 1,888,100 miles de pesos, por lo que se han clasificado como cobertura de flujos de efectivo. Los prestamos y los swaps de tasa de interes tienen los mismos terminos criticos.

El valor razonable de dichos instrumentos al 31 de marzo de 2024, ha sido reconocido dentro de otros resultados integrales como ganancia no realizada en swaps de tasa de interes.

## 6 OPERACIONES Y SALDOS CON PARTES RELACIONADAS

Servicios de asesoria Fibra Shop

Portafolios Inmobilarios, S.C.

Los saldos con partes relacionadas al 31 de marzo de 2024 y 31 de diciembre de 2023 se integral como sigue:

\begin{tabular}{l|c c}  & 2024 & 2023 \\ \hline Cuentas por pagar Fibra Shop

Portafolios Inmobilarios, S.C. & 22,514 & 23,170 \\ \end{tabular}

## 7 PasiVOS accumulados

\begin{tabular}{l|c c}  & 2024 & 2023 \\ \hline \hline \multirow{2}{*}{Interestes devengados pendientes de pago} & 76,131 & **70,534** \\  & Otros pasiVos accumulados & 211,278 & **191,995** \\  & Impuesto sobre traslado de dominio & 174,730 & **174,730** \\  & **Tota pasiVos accumulados** & **462,139** & **437,259** \\ \end{tabular}

## 8 CAPITAL CONTRIBUIDO

Los CBFIs emitidos por FSHOP otorgan a sus titulares el derecho a una parte de los beneficiios, productos y, si corresponde, valor residual de los activos o derechos de FSHOP, y del producto de la venta de activos o derechos de los bienes o fondo del fideicomiso, conforme a los terminos establecidos en el Contrato de Fideicomiso. Al 31 de marzo de 2024, el capital se integra por 477,883,423 CBFIs en circulacion.

## 9 INFORMACION FINANCIERA por SEGMENTOS

A continuacion, se presenta la informacion financiera por segmentos con informacion correspondiente al primer trimestre de 2024.

## 10 Utilidad Por Cbfi

A continuacion, se presenta la utilidad contable por certificado bursatil fiduciario FSHOP correspondiente a los ultimos periodos reportados:

## 11 DISTRIBRIOENES PAGADAS O DISPUESTAS

El Comite Tecnico de FSHOP ha determinado el pago de distribuciones trimestrales a los tenendores de los CBFI's, durante el periodo reportado se realizo una distribucion por un monto total de 60,000 miles de pesos (0.1371 por CBFI), correspondiente a la utilidad integral no auditada del primer trimestre de 2024.

## 12 ADMINISTRACION DE CAPITAL Y DE LOS RiesGOS FinanciEROS

Los objetivos y las politicas de la administracion de los riesgos financieros del Grupo son establecidos por su Comite Tecnico, de conformidad con su estatuto.

## 13 COMPROMISOS Y PASIVOS CONTINGENTES

A la fecha del balance no se tienen compromisos y pasivos contingentes adicionales por revelar.

## 14 INFORMACION DE PATTES RELACIONADAS

A continuacion se detallan las partes relacionadas con FSHOP mas importantes:

Grupo Cayon y Grupo FREL fueron cedentes del portafolio inicial de inversiones de FibraShop conforman el Fidiccomiso de Control. Dichos Grupos continuaran contribuyendo con su experiencia en el sector a la generacion de nuevas opportunadades de inversion para FibraShop.

Mediante el referido contratto de Fidiccomiso de Control, FibraShop cuenta con el derecho de preferencia para la adquisicion de inmuebles desarrollados por los dos grupos, operaciones que deberan ser aprobadas por el Comite Tecnico, con el voto favorable de la mayoria de los Consejeros Independientes. Adicionalmente, dicho Fidiccomiso de Control comprende una clausula de no competencia.

## 15 EVENTOS SUBSEUCENTES

No hay eventos subsecuentes que revelar a la fecha del reporte.